import { create } from 'zustand';
import { persist } from 'zustand/middleware';

interface LanguageState {
  language: 'en' | 'ar';
  t: (key: string) => string;
  setLanguage: (language: 'en' | 'ar') => void;
}

const translations = {
  en: {
    searchClient: "Search Client",
    search: "Search",
    searchResults: "Search Results",
    name: "Name",
    phoneNumber: "Phone Number",
    dateOfBirth: "Date of Birth",
    age: "Age",
    actions: "Actions",
    noResults: "No Results",
    clientFile: "Client File",
    printWorkOrder: "Print Work Order",
    invoiceSaved: "Invoice Saved!",
    invoiceNumber: "Invoice Number",
    error: "Error",
    errorSavingInvoice: "Error saving invoice",
    saving: "Saving...",
    clientSection: "Client Section",
    phoneColon: "Phone:",
    typeToSearch: "Type to search...",
    noClientsFound: "No clients found.",
    clientName: "Client Name",
    clientPhone: "Client Phone",
    patientID: "Patient ID",
    hideRx: "Hide RX",
    showRx: "Show RX",
    rightEyeAbbr: "R",
    leftEyeAbbr: "L",
    eye: "Eye",
    SPH: "SPH",
    CYL: "CYL",
    AXIS: "AXIS",
    ADD: "ADD",
    PD: "PD",
    optional: "Optional",
    glasses: "Glasses",
    contacts: "Contacts",
    noClientFile: "No Client File",
    lensSection: "Lens Section",
    searchTerm: "Search Term",
    searchExample: "Brand, Model...",
    noFramesFound: "No frames found.",
    selectedFrame: "Selected Frame",
    brand: "Brand",
    model: "Model",
    color: "Color",
    size: "Size",
    price: "Price",
    quantity: "Quantity",
    choose: "Choose",
    addFrameButton: "Add New Frame Manually",
    newFrameDetails: "New Frame Details",
    kwd: "KWD",
    saveFrame: "Save Frame",
    lensType: "Lens Type",
    coating: "Coating",
    thickness: "Thickness",
    skipLens: "Skip Lens",
    lensPrice: "Lens Price",
    coatingPrice: "Coating Price",
    thicknessPrice: "Thickness Price",
    total: "Total",
    discount: "Discount",
    deposit: "Deposit",
    paymentMethod: "Payment Method",
    remaining: "Remaining",
    authNumber: "Auth Number",
    next: "Next",
    previous: "Previous",
    submit: "Submit",
    cash: "Cash",
    knet: "KNET",
    visa: "Visa",
    mastercard: "MasterCard",
    invoiceDetails: "Invoice Details",
    invoiceType: "Invoice Type",
    date: "Date",
    totalAmount: "Total Amount",
    amountPaid: "Amount Paid",
    balanceDue: "Balance Due",
    paymentHistory: "Payment History",
    paymentDate: "Payment Date",
    paymentAmount: "Payment Amount",
    paymentMethodUsed: "Payment Method",
    noPaymentsRecorded: "No payments recorded for this invoice.",
    printReceipt: "Print Receipt",
    printInvoice: "Print Invoice",
    close: "Close",
    editInvoice: "Edit Invoice",
    deleteInvoice: "Delete Invoice",
    deleteConfirmation: "Are you sure you want to delete this invoice?",
    yes: "Yes",
    no: "No",
    invoiceDeleted: "Invoice Deleted",
    invoiceDeletedSuccessfully: "Invoice deleted successfully.",
    errorDeletingInvoice: "Error deleting invoice.",
    edit: "Edit",
    copy: "Copy",
    print: "Print",
    addNewFrame: "Add New Frame",
    addNewFrameTitle: "Add a new frame to inventory",
    addNewFrameDescription: "Enter the details for the new frame.",
    brandExample: "e.g., Ray-Ban",
    modelExample: "e.g., RB3447",
    colorExample: "e.g., Gold",
    sizeExample: "e.g., 50-21-145",
    pleaseEnterCompleteFrameDetails: "Please enter complete frame details.",
    pleaseEnterValidPrice: "Please enter a valid price.",
    pleaseEnterValidQuantity: "Please enter a valid quantity.",
    frameAddedSuccessfully: "Frame added successfully!",
    noFramesMatchingSearch: "No frames matching your search.",
    showAllFrames: "Show All Frames",
    printFrameLabels: "Print Frame Labels",
    selectFramesForLabels: "Select frames for printing labels.",
    cancel: "Cancel",
    saveFrame: "Save Frame",
    noFramesFound: "No frames found.",
    phoneSearchError: "Please enter a phone number to search.",
    searchTermError: "Please enter a search term.",
    frameDetailsError: "Please enter complete frame details.",
    priceError: "Please enter a valid price.",
    quantityError: "Please enter a valid quantity.",
    frameAddedSuccess: "Frame added successfully!",
    contactLensesTotal: "Contact Lenses Total",
    lensCount: "Lenses",
    pieces: "Pieces",
    remainingPayments: "Remaining Payments",
    duePayments: "View and manage due payments.",
    allInvoicesFullyPaid: "All invoices fully paid",
    noInvoicesRequirePayments: "No invoices require remaining payments. All transactions are complete.",
    totalInvoice: "Invoice Total",
    paid: "Paid",
    paymentHistoryColon: "Payment History:",
    recordNewPayment: "Record New Payment",
    recordPaymentForInvoice: "Record payment for invoice",
    totalAmountColon: "Total Amount:",
    previouslyPaidColon: "Previously Paid:",
    remainingAmountColon: "Remaining Amount:",
    remainingAfterPaymentColon: "Remaining After Payment:",
    paymentMethods: "Payment Methods",
    addPaymentMethod: "Add Payment Method",
    paymentMethodColon: "Payment Method",
    selectPaymentMethod: "Select payment method",
    amountKWDColon: "Amount (KWD)",
    authorizationNumber: "Authorization Number",
    totalPaidColon: "Total Payment:",
    confirmPayment: "Confirm Payment",
    paymentSuccessfullyRecorded: "Payment Successfully Recorded",
    paymentCompletedSuccessfully: "Payment completed successfully! Would you like to print the final invoice?",
    selectPrintLanguage: "Select Print Language",
    pleaseSelectLanguageForPrescription: "Please select the language for printing the prescription",
    printPrescription: "Print Prescription",
    clientProfile: "Client Profile",
    clientDetailsAndHistory: "Client details and transaction history",
    prescription: "Prescription",
    addNewRx: "Add New RX",
    addPrescriptionSuccessfully: "Prescription added successfully",
    selectPrintLanguageForPrescription: "Please select the language for printing the prescription",
    transactions: "Transactions",
    workOrders: "Work Orders",
    invoices: "Invoices",
    notes: "Notes",
    addNote: "Add Note",
    saveNote: "Save Note",
    noteSavedSuccessfully: "Note saved successfully",
    enterNoteHere: "Enter note here...",
    rxHistory: "RX History",
    rxDetails: "RX Details",
    rxDate: "RX Date",
    noRxHistoryAvailable: "No RX history available",
    printWorkOrderReceipt: "Print Work Order Receipt",
    workOrderDetails: "Work Order Details",
    patientDetails: "Patient Details",
    workOrderNumber: "Work Order Number",
    workOrderDate: "Work Order Date",
    lensDetails: "Lens Details",
    frameDetails: "Frame Details",
    coatingDetails: "Coating Details",
    totalPrice: "Total Price",
    signature: "Signature",
    customerSignature: "Customer Signature",
    staffSignature: "Staff Signature",
    printDate: "Print Date",
    printTime: "Print Time",
    printBy: "Print By",
    printReceiptForWorkOrder: "Print Receipt for Work Order",
    printReceiptForInvoice: "Print Receipt for Invoice",
    printReceiptForRefund: "Print Receipt for Refund",
    refundExchangeManagement: "Refund & Exchange Management",
    processRefundsAndExchanges: "Process refunds and product exchanges for customers",
    searchForInvoice: "Search for Invoice",
    searchForInvoiceByNumberNamePhone: "Search for an invoice by invoice number, customer name, or phone number",
    searchResultsFor: "Search Results",
    invoiceID: "Invoice ID",
    customer: "Customer",
    dateCreated: "Date Created",
    totalAmountKWD: "Total Amount (KWD)",
    status: "Status",
    select: "Select",
    refundInformation: "Refund Information",
    refundAmount: "Refund Amount",
    totalInvoiceAmount: "Total invoice amount",
    refundMethod: "Refund Method",
    selectRefundMethod: "Select refund method",
    refundReason: "Refund Reason",
    selectRefundReason: "Select refund reason",
    additionalNotes: "Additional Notes",
    enterAdditionalNotes: "Enter any additional notes here...",
    cancelRefund: "Cancel",
    processRefund: "Process Refund",
    allVisits: "All Visits",
    lastWeek: "Last Week",
    lastMonth: "Last Month",
    lastYear: "Last Year",
    visitDate: "Visit Date",
    filter: "Filter",
    noMatchingResultsFound: "No matching results found",
    pleaseEnterSearchTerm: "Please enter a search term",
    searchForFrame: "Search for frame",
    search: "Search",
  },
  ar: {
    searchClient: "البحث عن عميل",
    search: "بحث",
    searchResults: "نتائج البحث",
    name: "الاسم",
    phoneNumber: "رقم الهاتف",
    dateOfBirth: "تاريخ الميلاد",
    age: "العمر",
    actions: "الإجراءات",
    noResults: "لا توجد نتائج",
    clientFile: "ملف العميل",
    printWorkOrder: "طباعة أمر العمل",
    invoiceSaved: "تم حفظ الفاتورة!",
    invoiceNumber: "رقم الفاتورة",
    error: "خطأ",
    errorSavingInvoice: "خطأ في حفظ الفاتورة",
    saving: "جارٍ الحفظ...",
    clientSection: "بيانات العميل",
    phoneColon: "الهاتف:",
    typeToSearch: "اكتب للبحث...",
    noClientsFound: "لم يتم العثور على عملاء.",
    clientName: "اسم العميل",
    clientPhone: "هاتف العميل",
    patientID: "معرف المريض",
    hideRx: "إخفاء الروشتة",
    showRx: "إظهار الروشتة",
    rightEyeAbbr: "يمين",
    leftEyeAbbr: "يسار",
    eye: "العين",
    SPH: "SPH",
    CYL: "CYL",
    AXIS: "AXIS",
    ADD: "ADD",
    PD: "PD",
    optional: "اختياري",
    glasses: "نظارات",
    contacts: "عدسات",
    noClientFile: "لا يوجد ملف عميل",
    lensSection: "بيانات العدسة",
    searchTerm: "كلمة البحث",
    searchExample: "الماركة، الموديل...",
    noFramesFound: "لم يتم العثور على إطارات.",
    selectedFrame: "الإطار المحدد",
    brand: "الماركة",
    model: "الموديل",
    color: "اللون",
    size: "المقاس",
    price: "السعر",
    quantity: "الكمية",
    choose: "اختر",
    addFrameButton: "إضافة إطار جديد يدويًا",
    newFrameDetails: "تفاصيل الإطار الجديد",
    kwd: "د.ك",
    saveFrame: "حفظ الإطار",
    lensType: "نوع العدسة",
    coating: "الطلاء",
    thickness: "السُمك",
    skipLens: "تخطي العدسة",
    lensPrice: "سعر العدسة",
    coatingPrice: "سعر الطلاء",
    thicknessPrice: "سعر السُمك",
    total: "الإجمالي",
    discount: "الخصم",
    deposit: "المقدم",
    paymentMethod: "طريقة الدفع",
    remaining: "المتبقي",
    authNumber: "رقم التفويض",
    next: "التالي",
    previous: "السابق",
    submit: "إرسال",
    cash: "نقداً",
    knet: "كي نت",
    visa: "Visa",
    mastercard: "MasterCard",
    invoiceDetails: "تفاصيل الفاتورة",
    invoiceType: "نوع الفاتورة",
    date: "التاريخ",
    totalAmount: "المبلغ الإجمالي",
    amountPaid: "المبلغ المدفوع",
    balanceDue: "الرصيد المستحق",
    paymentHistory: "سجل الدفع",
    paymentDate: "تاريخ الدفع",
    paymentAmount: "مبلغ الدفع",
    paymentMethodUsed: "طريقة الدفع المستخدمة",
    noPaymentsRecorded: "لا توجد مدفوعات مسجلة لهذه الفاتورة.",
    printReceipt: "طباعة الإيصال",
    printInvoice: "طباعة الفاتورة",
    close: "إغلاق",
    editInvoice: "تعديل الفاتورة",
    deleteInvoice: "حذف الفاتورة",
    deleteConfirmation: "هل أنت متأكد أنك تريد حذف هذه الفاتورة؟",
    yes: "نعم",
    no: "لا",
    invoiceDeleted: "تم حذف الفاتورة",
    invoiceDeletedSuccessfully: "تم حذف الفاتورة بنجاح.",
    errorDeletingInvoice: "خطأ في حذف الفاتورة.",
    edit: "تعديل",
    copy: "نسخ",
    print: "طباعة",
    addNewFrame: "إضافة إطار جديد",
    addNewFrameTitle: "إضافة إطار جديد إلى المخزون",
    addNewFrameDescription: "أدخل تفاصيل الإطار الجديد.",
    brandExample: "مثال: Ray-Ban",
    modelExample: "مثال: RB3447",
    colorExample: "مثال: ذهبي",
    sizeExample: "مثال: 50-21-145",
    pleaseEnterCompleteFrameDetails: "الرجاء إدخال تفاصيل الإطار كاملة.",
    pleaseEnterValidPrice: "الرجاء إدخال سعر صالح.",
    pleaseEnterValidQuantity: "الرجاء إدخال كمية صالحة.",
    frameAddedSuccessfully: "تمت إضافة الإطار بنجاح!",
    noFramesMatchingSearch: "لا توجد إطارات تطابق بحثك.",
    showAllFrames: "عرض جميع الإطارات",
    printFrameLabels: "طباعة ملصقات الإطارات",
    selectFramesForLabels: "حدد الإطارات لطباعة الملصقات.",
    cancel: "إلغاء",
    saveFrame: "حفظ الإطار",
    noFramesFound: "لم يتم العثور على أية إطارات",
    phoneSearchError: "الرجاء إدخال رقم هاتف للبحث.",
    searchTermError: "الرجاء إدخال مصطلح البحث.",
    frameDetailsError: "الرجاء إدخال تفاصيل الإطار كاملة.",
    priceError: "الرجاء إدخال سعر صالح.",
    quantityError: "الرجاء إدخال كمية صالحة.",
    frameAddedSuccess: "تمت إضافة الإطار بنجاح!",
    contactLensesTotal: "إجمالي العدسات اللاصقة",
    lensCount: "عدسة",
    pieces: "قطعة",
    remainingPayments: "المدفوعات المتبقية",
    duePayments: "عرض وإدارة المدفوعات المستحقة.",
    allInvoicesFullyPaid: "جميع الفواتير مدفوعة بالكامل",
    noInvoicesRequirePayments: "لا توجد فواتير تتطلب مدفوعات متبقية. جميع المعاملات مكتملة.",
    totalInvoice: "إجمالي الفاتورة",
    paid: "مدفوع",
    paymentHistoryColon: "سجل الدفعات:",
    recordNewPayment: "تسجيل دفعة جديدة",
    recordPaymentForInvoice: "تسجيل دفعة للفاتورة",
    totalAmountColon: "المبلغ الإجمالي:",
    previouslyPaidColon: "المدفوع سابقاً:",
    remainingAmountColon: "المبلغ المتبقي:",
    remainingAfterPaymentColon: "المتبقي بعد الدفع:",
    paymentMethods: "طرق الدفع",
    addPaymentMethod: "إضافة طريقة دفع",
    paymentMethodColon: "طريقة الدفع",
    selectPaymentMethod: "اختر طريقة الدفع",
    amountKWDColon: "المبلغ (د.ك)",
    authorizationNumber: "رقم التفويض",
    totalPaidColon: "إجمالي المدفوع:",
    confirmPayment: "تأكيد الدفع",
    paymentSuccessfullyRecorded: "تم تسجيل الدفع بنجاح",
    paymentCompletedSuccessfully: "تم إكمال الدفع بنجاح! هل ترغب في طباعة الفاتورة النهائية؟",
    selectPrintLanguage: "اختر لغة الطباعة",
    pleaseSelectLanguageForPrescription: "الرجاء اختيار لغة طباعة الوصفة الطبية",
    printPrescription: "طباعة الوصفة الطبية",
    clientProfile: "ملف العميل",
    clientDetailsAndHistory: "تفاصيل بيانات العميل وسجل المعاملات",
    prescription: "الوصفة الطبية",
    addNewRx: "إضافة وصفة جديدة",
    addPrescriptionSuccessfully: "تمت إضافة الوصفة الطبية بنجاح",
    selectPrintLanguageForPrescription: "الرجاء اختيار لغة طباعة الوصفة الطبية",
    transactions: "المعاملات",
    workOrders: "أوامر العمل",
    invoices: "الفواتير",
    notes: "ملاحظات",
    addNote: "إضافة ملاحظة",
    saveNote: "حفظ الملاحظة",
    noteSavedSuccessfully: "تم حفظ الملاحظة بنجاح",
    enterNoteHere: "أدخل ملاحظة هنا...",
    rxHistory: "سجل الوصفات الطبية",
    rxDetails: "تفاصيل الوصفة الطبية",
    rxDate: "تاريخ الوصفة الطبية",
    noRxHistoryAvailable: "لا يوجد سجل للوصفات الطبية",
    printWorkOrderReceipt: "طباعة إيصال أمر العمل",
    workOrderDetails: "تفاصيل أمر العمل",
    patientDetails: "بيانات المريض",
    workOrderNumber: "رقم أمر العمل",
    workOrderDate: "تاريخ أمر العمل",
    lensDetails: "تفاصيل العدسة",
    frameDetails: "تفاصيل الإطار",
    coatingDetails: "تفاصيل الطلاء",
    totalPrice: "السعر الإجمالي",
    signature: "التوقيع",
    customerSignature: "توقيع العميل",
    staffSignature: "توقيع الموظف",
    printDate: "تاريخ الطباعة",
    printTime: "وقت الطباعة",
    printBy: "طباعة بواسطة",
    printReceiptForWorkOrder: "طباعة إيصال لأمر العمل",
    printReceiptForInvoice: "طباعة إيصال للفاتورة",
    printReceiptForRefund: "طباعة إيصال للاسترداد",
    refundExchangeManagement: "إدارة استرداد الأموال والاستبدال",
    processRefundsAndExchanges: "معالجة استرداد الأموال واستبدال المنتجات للعملاء",
    searchForInvoice: "البحث عن فاتورة",
    searchForInvoiceByNumberNamePhone: "ابحث عن الفاتورة بواسطة رقم الفاتورة، اسم العميل، أو رقم الهاتف",
    searchResultsFor: "نتائج البحث",
    invoiceID: "رقم الفاتورة",
    customer: "العميل",
    dateCreated: "تاريخ الإنشاء",
    totalAmountKWD: "المبلغ الإجمالي (د.ك)",
    status: "الحالة",
    select: "تحديد",
    refundInformation: "معلومات الاسترداد",
    refundAmount: "مبلغ الاسترداد",
    totalInvoiceAmount: "المبلغ الإجمالي للفاتورة",
    refundMethod: "طريقة الاسترداد",
    selectRefundMethod: "حدد طريقة الاسترداد",
    refundReason: "سبب الاسترداد",
    selectRefundReason: "حدد سبب الاسترداد",
    additionalNotes: "ملاحظات إضافية",
    enterAdditionalNotes: "أدخل أي ملاحظات إضافية هنا...",
    cancelRefund: "إلغاء",
    processRefund: "معالجة الاسترداد",
    allVisits: "جميع الزيارات",
    lastWeek: "الأسبوع الماضي",
    lastMonth: "الشهر الماضي",
    lastYear: "السنة الماضية",
    visitDate: "تاريخ الزيارة",
    filter: "فلتر",
    noMatchingResultsFound: "لم يتم العثور على نتائج مطابقة",
    pleaseEnterSearchTerm: "الرجاء إدخال مصطلح البحث",
    searchForFrame: "البحث عن إطار",
    search: "بحث",
  },
};

export const useLanguageStore = create<LanguageState>()(
  persist(
    (set, get) => ({
      language: (localStorage.getItem('language') as 'en' | 'ar') || 'en',
      t: (key: string) => {
        const lang = get().language;
        return translations[lang][key] || key;
      },
      setLanguage: (language: 'en' | 'ar') => {
        set({ language });
      },
    }),
    {
      name: 'language-storage',
      storage: {
        getItem: (name: string) => {
          const value = localStorage.getItem(name);
          return value ? JSON.parse(value) : null;
        },
        setItem: (name: string, value: any) => {
          localStorage.setItem(name, JSON.stringify(value));
        },
        removeItem: (name: string) => {
          localStorage.removeItem(name);
        },
      },
    }
  )
);
