
import { create } from "zustand";

interface LanguageState {
  language: string;
  setLanguage: (lang: string) => void;
  t: (key: string) => string;
  translations: Record<string, Record<string, string>>;
}

export const useLanguageStore = create<LanguageState>((set, get) => ({
  language: localStorage.getItem("language") || "ar",
  setLanguage: (lang: string) => {
    localStorage.setItem("language", lang);
    set({ language: lang });
  },
  t: (key: string) => {
    const { language, translations } = get();
    return translations[language]?.[key] || key;
  },
  translations: {
    en: {
      // English translations
      home: "Home",
      patients: "Patients",
      inventory: "Inventory",
      invoices: "Invoices",
      workOrders: "Work Orders",
      dashboard: "Dashboard",
      settings: "Settings",
      logout: "Logout",
      searchPatients: "Search patients...",
      createPatient: "Create Patient",
      patientDetails: "Patient Details",
      editPatient: "Edit Patient",
      createPrescription: "Create Prescription",
      savePrescription: "Save Prescription",
      prescriptionHistory: "Prescription History",
      date: "Date",
      doctor: "Doctor",
      actions: "Actions",
      viewPrescription: "View Prescription",
      patientInformation: "Patient Information",
      personalInformation: "Personal Information",
      prescriptions: "Prescriptions",
      name: "Name",
      phone: "Phone",
      email: "Email",
      nationalId: "National ID",
      civilId: "Civil ID",
      dateOfBirth: "Date of Birth",
      gender: "Gender",
      male: "Male",
      female: "Female",
      address: "Address",
      notes: "Notes",
      save: "Save",
      cancel: "Cancel",
      prescriptionDetails: "Prescription Details",
      sphere: "Sphere",
      cylinder: "Cylinder",
      axis: "Axis",
      add: "Add",
      pd: "PD",
      right: "Right",
      left: "Left",
      selectLensType: "Select Lens Type",
      selectCoatings: "Select Coatings",
      selectThickness: "Select Thickness",
      frameOnly: "Frame Only (No Lens)",
      distance: "Distance",
      reading: "Reading",
      progressive: "Progressive",
      bifocal: "Bifocal",
      sunglasses: "Sunglasses",
      noCoating: "No Coating",
      noCoatingDesc: "Skip lens coating",
      noThickness: "No Thickness",
      noThicknessDesc: "Standard thickness",
      selectLensTypeFirst: "Please select a lens type first",
      addLens: "Add Lens",
      searchFrames: "Search frames...",
      brand: "Brand",
      model: "Model",
      color: "Color",
      size: "Size",
      price: "Price",
      quantity: "Quantity",
      edit: "Edit",
      delete: "Delete",
      addFrame: "Add Frame",
      frameDetails: "Frame Details",
      createFrame: "Create Frame",
      editFrame: "Edit Frame",
      updateFrame: "Update Frame",
      saveFrame: "Save Frame",
      duplicateFrame: "Duplicate Frame",
      removeFrame: "Remove Frame",
      confirmDelete: "Confirm Delete",
      areYouSure: "Are you sure you want to delete this item?",
      thisActionCannot: "This action cannot be undone.",
      yes: "Yes",
      no: "No",
      createWorkOrder: "Create Work Order",
      workOrderDetails: "Work Order Details",
      patient: "Patient",
      status: "Status",
      appointmentDate: "Appointment Date",
      createInvoice: "Create Invoice",
      viewInvoice: "View Invoice",
      printWorkOrder: "Print Work Order",
      editWorkOrder: "Edit Work Order",
      deleteWorkOrder: "Delete Work Order",
      select: "Select",
      selectPatient: "Select Patient",
      search: "Search",
      rxDetails: "Prescription Details",
      lensDetails: "Lens Details",
      frameDetails: "Frame Details",
      lensType: "Lens Type",
      coating: "Coating",
      thickness: "Thickness",
      frame: "Frame",
      status_pending: "Pending",
      status_inProgress: "In Progress",
      status_readyForPickup: "Ready for Pickup",
      status_completed: "Completed",
      status_cancelled: "Cancelled",
      createLens: "Create Lens",
      lensName: "Lens Name",
      lensDescription: "Lens Description",
      lensCategory: "Category",
      lensPrice: "Lens Price",
      saveChanges: "Save Changes",
      addCoating: "Add Coating",
      coatingName: "Coating Name",
      coatingDescription: "Coating Description",
      coatingAppliesTo: "Applies To",
      coatingPrice: "Coating Price",
      addThickness: "Add Thickness",
      thicknessName: "Thickness Name",
      thicknessDescription: "Thickness Description",
      thicknessAppliesTo: "Applies To",
      thicknessPrice: "Thickness Price",
      kwd: "KWD",
      enterValidPrice: "Please enter a valid price",
      dashboardTitle: "Dashboard",
      todaySummary: "Today's Summary",
      totalAppointments: "Total Appointments",
      pendingOrders: "Pending Orders",
      readyForPickup: "Ready for Pickup",
      monthlyRevenue: "Monthly Revenue",
      todaysRevenue: "Today's Revenue",
      recentInvoices: "Recent Invoices",
      recentWorkOrders: "Recent Work Orders",
      invoiceTitle: "Create Invoice",
      clientSection: "Client",
      productSection: "Products",
      paymentSection: "Payment",
      summarySection: "Summary",
      invoiceSummary: "Invoice Summary",
      clientInformation: "Client Information",
      waitingForClientData: "Waiting for client details...",
      waitingForProductData: "Products will be shown here...",
      waitingForPaymentData: "Payment information will be displayed here...",
      subtotal: "Subtotal",
      discount: "Discount",
      total: "Total",
      deposit: "Deposit",
      remaining: "Remaining",
      paidInFull: "Paid in Full",
      previous: "Previous",
      next: "Next",
      invoice: "Invoice",
      print: "Print",
      close: "Close",
      selectType: "Select Type",
      glassesInvoice: "Glasses",
      contactsInvoice: "Contact Lenses",
      examInvoice: "Eye Exam",
      addDiscount: "Add Discount",
      applyDiscount: "Apply Discount",
      fixedAmount: "Fixed Amount",
      percentage: "Percentage",
      addDeposit: "Add Deposit",
      enterAmount: "Enter Amount",
      paymentMethod: "Payment Method",
      cash: "Cash",
      knet: "K-NET",
      creditCard: "Credit Card",
      paymentDetails: "Payment Details",
      addPayment: "Add Payment",
      confirmInvoice: "Confirm Invoice",
      selectFrame: "Select Frame",
      selectContactLenses: "Select Contact Lenses",
      authNumber: "Authorization Number",
      enterAuthNumber: "Enter Auth Number",
      finalizeInvoice: "Finalize Invoice",
      invoiceCreated: "Invoice Created Successfully",
      invoiceCreatedDesc: "The invoice has been created and saved successfully.",
      printInvoice: "Print Invoice",
      downloadInvoice: "Download Invoice",
      createNewInvoice: "Create New Invoice",
      invoiceDetails: "Invoice Details",
      invoiceNumber: "Invoice No.",
      workOrderNumber: "Work Order No.",
      date: "Date",
      invoiceItems: "Invoice Items",
      item: "Item",
      unitPrice: "Unit Price",
      amount: "Amount",
      frameNotFound: "Frame not found",
      errorGeneratingQRCode: "Error generating QR code",
      noFramesSelected: "No frames selected",
      noFramesFound: "No frames found",
      labelPrintedSuccessfully: "Label printed successfully",
      labelsPrintedSuccessfully: "Labels printed successfully",
      contactLenses: "Contact Lenses",
      bc: "BC",
      diameter: "Diameter",
      power: "Power",
      frameBarcode: "Frame Barcode",
      scanBarcode: "Scan Barcode",
      manualEntry: "Manual Entry",
      scanFrameBarcode: "Scan Frame Barcode",
      scanningInProgress: "Scanning in progress...",
      scanAgain: "Scan Again",
      enterFrameId: "Enter Frame ID",
      frameFound: "Frame Found",
      frameNotFoundDesc: "No frame found with this ID",
      retry: "Retry",
      add: "Add",
      history: "History",
      historyDate: "Date",
      historyType: "Type",
      historyDetails: "Details",
    },
    ar: {
      // Arabic translations
      home: "الرئيسية",
      patients: "المرضى",
      inventory: "المخزون",
      invoices: "الفواتير",
      workOrders: "أوامر العمل",
      dashboard: "لوحة التحكم",
      settings: "الإعدادات",
      logout: "تسجيل الخروج",
      searchPatients: "بحث عن مرضى...",
      createPatient: "إضافة مريض",
      patientDetails: "تفاصيل المريض",
      editPatient: "تعديل بيانات المريض",
      createPrescription: "إنشاء وصفة طبية",
      savePrescription: "حفظ الوصفة",
      prescriptionHistory: "سجل الوصفات الطبية",
      date: "التاريخ",
      doctor: "الطبيب",
      actions: "الإجراءات",
      viewPrescription: "عرض الوصفة",
      patientInformation: "معلومات المريض",
      personalInformation: "المعلومات الشخصية",
      prescriptions: "الوصفات الطبية",
      name: "الاسم",
      phone: "الهاتف",
      email: "البريد الإلكتروني",
      nationalId: "الرقم القومي",
      civilId: "الرقم المدني",
      dateOfBirth: "تاريخ الميلاد",
      gender: "الجنس",
      male: "ذكر",
      female: "أنثى",
      address: "العنوان",
      notes: "ملاحظات",
      save: "حفظ",
      cancel: "إلغاء",
      prescriptionDetails: "تفاصيل الوصفة",
      sphere: "المجال",
      cylinder: "الاسطوانة",
      axis: "المحور",
      add: "إضافة",
      pd: "المسافة بين البؤبؤين",
      right: "اليمين",
      left: "اليسار",
      selectLensType: "اختيار نوع العدسة",
      selectCoatings: "اختيار الطلاء",
      selectThickness: "اختيار السمك",
      frameOnly: "إطار فقط (بدون عدسات)",
      distance: "للبعيد",
      reading: "للقراءة",
      progressive: "متدرجة",
      bifocal: "ثنائية البؤرة",
      sunglasses: "نظارات شمسية",
      noCoating: "بدون طلاء",
      noCoatingDesc: "تخطي طلاء العدسة",
      noThickness: "بدون سمك إضافي",
      noThicknessDesc: "السمك القياسي",
      selectLensTypeFirst: "الرجاء اختيار نوع العدسة أولاً",
      addLens: "إضافة عدسة",
      searchFrames: "البحث عن إطارات...",
      brand: "الماركة",
      model: "الموديل",
      color: "اللون",
      size: "الحجم",
      price: "السعر",
      quantity: "الكمية",
      edit: "تعديل",
      delete: "حذف",
      addFrame: "إضافة إطار",
      frameDetails: "تفاصيل الإطار",
      createFrame: "إنشاء إطار",
      editFrame: "تعديل إطار",
      updateFrame: "تحديث الإطار",
      saveFrame: "حفظ الإطار",
      duplicateFrame: "نسخ الإطار",
      removeFrame: "إزالة الإطار",
      confirmDelete: "تأكيد الحذف",
      areYouSure: "هل أنت متأكد أنك تريد حذف هذا العنصر؟",
      thisActionCannot: "لا يمكن التراجع عن هذا الإجراء.",
      yes: "نعم",
      no: "لا",
      createWorkOrder: "إنشاء أمر عمل",
      workOrderDetails: "تفاصيل أمر العمل",
      patient: "المريض",
      status: "الحالة",
      appointmentDate: "تاريخ الموعد",
      createInvoice: "إنشاء فاتورة",
      viewInvoice: "عرض الفاتورة",
      printWorkOrder: "طباعة أمر العمل",
      editWorkOrder: "تعديل أمر العمل",
      deleteWorkOrder: "حذف أمر العمل",
      select: "اختيار",
      selectPatient: "اختر مريض",
      search: "بحث",
      rxDetails: "تفاصيل الوصفة",
      lensDetails: "تفاصيل العدسة",
      frameDetails: "تفاصيل الإطار",
      lensType: "نوع العدسة",
      coating: "طلاء العدسة",
      thickness: "سمك العدسة",
      frame: "الإطار",
      status_pending: "قيد الانتظار",
      status_inProgress: "قيد التنفيذ",
      status_readyForPickup: "جاهز للاستلام",
      status_completed: "مكتمل",
      status_cancelled: "ملغي",
      createLens: "إنشاء عدسة",
      lensName: "اسم العدسة",
      lensDescription: "وصف العدسة",
      lensCategory: "الفئة",
      lensPrice: "سعر العدسة",
      saveChanges: "حفظ التغييرات",
      addCoating: "إضافة طلاء",
      coatingName: "اسم الطلاء",
      coatingDescription: "وصف الطلاء",
      coatingAppliesTo: "ينطبق على",
      coatingPrice: "سعر الطلاء",
      addThickness: "إضافة سمك",
      thicknessName: "اسم السمك",
      thicknessDescription: "وصف السمك",
      thicknessAppliesTo: "ينطبق على",
      thicknessPrice: "سعر السمك",
      kwd: "د.ك",
      enterValidPrice: "الرجاء إدخال سعر صحيح",
      dashboardTitle: "لوحة التحكم",
      todaySummary: "ملخص اليوم",
      totalAppointments: "إجمالي المواعيد",
      pendingOrders: "الطلبات المعلقة",
      readyForPickup: "جاهز للاستلام",
      monthlyRevenue: "الإيرادات الشهرية",
      todaysRevenue: "إيرادات اليوم",
      recentInvoices: "أحدث الفواتير",
      recentWorkOrders: "أحدث أوامر العمل",
      invoiceTitle: "إنشاء فاتورة",
      clientSection: "العميل",
      productSection: "المنتجات",
      paymentSection: "الدفع",
      summarySection: "الملخص",
      invoiceSummary: "ملخص الفاتورة",
      clientInformation: "معلومات العميل",
      waitingForClientData: "بانتظار تفاصيل العميل...",
      waitingForProductData: "سيتم عرض المنتجات هنا...",
      waitingForPaymentData: "سيتم عرض معلومات الدفع هنا...",
      subtotal: "المجموع الفرعي",
      discount: "الخصم",
      total: "الإجمالي",
      deposit: "العربون",
      remaining: "المتبقي",
      paidInFull: "تم الدفع بالكامل",
      previous: "السابق",
      next: "التالي",
      invoice: "الفاتورة",
      print: "طباعة",
      close: "إغلاق",
      selectType: "اختر النوع",
      glassesInvoice: "نظارات",
      contactsInvoice: "عدسات لاصقة",
      examInvoice: "فحص النظر",
      addDiscount: "إضافة خصم",
      applyDiscount: "تطبيق الخصم",
      fixedAmount: "مبلغ محدد",
      percentage: "نسبة مئوية",
      addDeposit: "إضافة عربون",
      enterAmount: "أدخل المبلغ",
      paymentMethod: "طريقة الدفع",
      cash: "نقدي",
      knet: "كي نت",
      creditCard: "بطاقة ائتمان",
      paymentDetails: "تفاصيل الدفع",
      addPayment: "إضافة دفعة",
      confirmInvoice: "تأكيد الفاتورة",
      selectFrame: "اختيار الإطار",
      selectContactLenses: "اختيار العدسات اللاصقة",
      authNumber: "رقم التفويض",
      enterAuthNumber: "أدخل رقم التفويض",
      finalizeInvoice: "إنهاء الفاتورة",
      invoiceCreated: "تم إنشاء الفاتورة بنجاح",
      invoiceCreatedDesc: "تم إنشاء الفاتورة وحفظها بنجاح.",
      printInvoice: "طباعة الفاتورة",
      downloadInvoice: "تحميل الفاتورة",
      createNewInvoice: "إنشاء فاتورة جديدة",
      invoiceDetails: "تفاصيل الفاتورة",
      invoiceNumber: "رقم الفاتورة",
      workOrderNumber: "رقم أمر العمل",
      date: "التاريخ",
      invoiceItems: "عناصر الفاتورة",
      item: "العنصر",
      unitPrice: "سعر الوحدة",
      amount: "المبلغ",
      frameNotFound: "الإطار غير موجود",
      errorGeneratingQRCode: "خطأ في إنشاء رمز الاستجابة السريعة",
      noFramesSelected: "لم يتم اختيار أي إطارات",
      noFramesFound: "لم يتم العثور على إطارات",
      labelPrintedSuccessfully: "تمت طباعة الملصق بنجاح",
      labelsPrintedSuccessfully: "تمت طباعة الملصقات بنجاح",
      contactLenses: "العدسات اللاصقة",
      bc: "BC",
      diameter: "القطر",
      power: "القوة",
      frameBarcode: "باركود الإطار",
      scanBarcode: "مسح الباركود",
      manualEntry: "إدخال يدوي",
      scanFrameBarcode: "مسح باركود الإطار",
      scanningInProgress: "جاري المسح...",
      scanAgain: "مسح مرة أخرى",
      enterFrameId: "أدخل معرف الإطار",
      frameFound: "تم العثور على الإطار",
      frameNotFoundDesc: "لم يتم العثور على إطار بهذا المعرف",
      retry: "إعادة المحاولة",
      add: "إضافة",
      history: "السجل",
      historyDate: "التاريخ",
      historyType: "النوع",
      historyDetails: "التفاصيل",
    }
  }
}));
