import { create } from 'zustand';

type LanguageStore = {
  language: 'en' | 'ar';
  setLanguage: (language: 'en' | 'ar') => void;
  t: (key: keyof (typeof translations)['en']) => string;
};

export const useLanguageStore = create<LanguageStore>((set, get) => ({
  language: 'en',
  setLanguage: (language) => set({ language }),
  t: (key) => {
    const { language } = get();
    // @ts-ignore - Key may not exist in both languages
    return translations[language][key] || key;
  }
}));

export const translations = {
  en: {
    // General UI
    save: "Save",
    cancel: "Cancel",
    edit: "Edit",
    delete: "Delete",
    success: "Success",
    error: "Error",
    loading: "Loading...",
    requiredField: "This field is required.",
    successMessage: "Operation completed successfully!",
    dataError: "Data Error",
    fillAllRequiredFields: "Please fill in all required fields.",
    close: "Close",
    view: "View",
    actions: "Actions",
    date: "Date",
    right: "Right",
    left: "Left",
    addNew: "Add New",
    search: "Search",
    clear: "Clear",
    print: "Print",
    choose: "Choose",
    day: "Day",
    month: "Month",
    year: "Year",
    fullName: "Full Name",
    phoneNumber: "Phone Number",
    enterValue: "Enter value",

    // Patient Management
    patientManagementTitle: "Patient Management",
    createClientTitle: "Create Client",
    clientListTitle: "Client List",
    personalInfo: "Personal Information",
    name: "Name",
    phone: "Phone",
    dateOfBirth: "Date of Birth",
    clientDidntShareDOB: "Client didn't share date of birth",
    notes: "Notes",
    saveAndContinue: "Save & Continue",
    successMessage: "Operation completed successfully!",
    noClients: "No clients found.",
    clientDetails: "Client Details",
    editClient: "Edit Client",
    deleteClient: "Delete Client",
    deleteConfirmation: "Are you sure you want to delete this client?",
    clientDeletedSuccessfully: "Client deleted successfully!",
    addNewClient: "Add New Client",
    prescriptionGlasses: "Prescription Glasses",
    contactLensesTab: "Contact Lenses",
    noContactLensRx: "No contact lens prescription found for this client.",
    noContactLensRxDescription: "Add a contact lens prescription to this client to keep track of their vision correction needs.",
    contactLensPrescription: "Contact Lens Prescription",
    notesPlaceholder: "Add notes about this client...",

    // Invoice
    invoiceTitle: "Invoice",
    invoiceDetails: "Invoice Details",
    createInvoice: "Create Invoice",
    editInvoice: "Edit Invoice",
    deleteInvoice: "Delete Invoice",
    invoiceNumber: "Invoice Number",
    dateIssued: "Date Issued",
    dueDate: "Due Date",
    billTo: "Bill To",
    items: "Items",
    addItem: "Add Item",
    description: "Description",
    quantity: "Quantity",
    unitPrice: "Unit Price",
    total: "Total",
    subtotal: "Subtotal",
    tax: "Tax",
    discount: "Discount",
    amountDue: "Amount Due",
    paymentStatus: "Payment Status",
    paid: "Paid",
    unpaid: "Unpaid",
    overdue: "Overdue",
    partiallyPaid: "Partially Paid",
    invoiceCreatedSuccessfully: "Invoice created successfully!",
    invoiceUpdatedSuccessfully: "Invoice updated successfully!",
    invoiceDeletedSuccessfully: "Invoice deleted successfully!",
    noInvoices: "No invoices found.",
    markAsPaid: "Mark as Paid",
    markAsUnpaid: "Mark as Unpaid",
    paymentReceivedSuccessfully: "Payment received successfully!",
    paymentNotReceived: "Payment status updated to Unpaid.",
    issueDate: "Issue Date",
    generateInvoice: "Generate Invoice",
    downloadInvoice: "Download Invoice",
    printInvoice: "Print Invoice",
    sendInvoice: "Send Invoice",
    invoiceSettings: "Invoice Settings",
    companyName: "Company Name",
    companyAddress: "Company Address",
    companyLogo: "Company Logo",
    taxRate: "Tax Rate",
    discountRate: "Discount Rate",
    invoiceSettingsSaved: "Invoice settings saved successfully!",
    addPayment: "Add Payment",
    paymentDate: "Payment Date",
    paymentAmount: "Payment Amount",
    paymentMethod: "Payment Method",
    paymentAddedSuccessfully: "Payment added successfully!",
    editPayment: "Edit Payment",
    deletePayment: "Delete Payment",
    paymentDeletedSuccessfully: "Payment deleted successfully!",
    areYouSureDeletePayment: "Are you sure you want to delete this payment?",
    paymentHistory: "Payment History",
    noPaymentsFound: "No payments found.",
    workOrder: "Work Order",
    workOrderNumber: "Work Order Number",
    createWorkOrder: "Create Work Order",
    editWorkOrder: "Edit Work Order",
    deleteWorkOrder: "Delete Work Order",
    workOrderCreatedSuccessfully: "Work order created successfully!",
    workOrderUpdatedSuccessfully: "Work order updated successfully!",
    workOrderDeletedSuccessfully: "Work order deleted successfully!",
    noWorkOrdersFound: "No work orders found.",
    workOrderDetails: "Work Order Details",
    customerDetails: "Customer Details",
    workOrderStatus: "Work Order Status",
    open: "Open",
    inProgress: "In Progress",
    completed: "Completed",
    cancelled: "Cancelled",
    workOrderSettings: "Work Order Settings",
    workOrderSettingsSaved: "Work order settings saved successfully!",
    prefix: "Prefix",
    nextNumber: "Next Number",
    workOrderPrefix: "Work Order Prefix",
    workOrderNextNumber: "Work Order Next Number",
    workOrderSettingsPrefix: "Work Order Settings Prefix",
    workOrderSettingsNextNumber: "Work Order Settings Next Number",
    workOrderSettingsPrefixPlaceholder: "Enter work order prefix",
    workOrderSettingsNextNumberPlaceholder: "Enter work order next number",
    workOrderSettingsPrefixRequired: "Work order prefix is required",
    workOrderSettingsNextNumberRequired: "Work order next number is required",
    workOrderSettingsPrefixInvalid: "Work order prefix is invalid",
    workOrderSettingsNextNumberInvalid: "Work order next number is invalid",
    workOrderSettingsPrefixTooLong: "Work order prefix is too long",
    workOrderSettingsNextNumberTooLong: "Work order next number is too long",
    workOrderSettingsPrefixTooShort: "Work order prefix is too short",
    workOrderSettingsNextNumberTooShort: "Work order next number is too short",
    workOrderSettingsPrefixPattern: "^[a-zA-Z0-9]*$",
    workOrderSettingsNextNumberPattern: "^[0-9]*$",
    workOrderSettingsPrefixPatternMessage: "Work order prefix must be alphanumeric",
    workOrderSettingsNextNumberPatternMessage: "Work order next number must be numeric",
    workOrderSettingsPrefixTooLongMessage: "Work order prefix must be less than 10 characters",
    workOrderSettingsNextNumberTooLongMessage: "Work order next number must be less than 10 characters",
    workOrderSettingsPrefixTooShortMessage: "Work order prefix must be at least 3 characters",
    workOrderSettingsNextNumberTooShortMessage: "Work order next number must be at least 3 characters",
    workOrderSettingsPrefixRequiredMessage: "Work order prefix is required",
    workOrderSettingsNextNumberRequiredMessage: "Work order next number is required",
    workOrderSettingsPrefixInvalidMessage: "Work order prefix is invalid",
    workOrderSettingsNextNumberInvalidMessage: "Work order next number is invalid",
    workOrderSettingsPrefixTooLongMessage: "Work order prefix is too long",
    workOrderSettingsNextNumberTooLongMessage: "Work order next number is too long",
    workOrderSettingsPrefixTooShortMessage: "Work order prefix is too short",
    workOrderSettingsNextNumberTooShortMessage: "Work order next number is too short",
    workOrderSettingsPrefixPatternMessage: "Work order prefix must be alphanumeric",
    workOrderSettingsNextNumberPatternMessage: "Work order next number must be numeric",
    workOrderSettingsPrefixTooLongMessage: "Work order prefix must be less than 10 characters",
    workOrderSettingsNextNumberTooLongMessage: "Work order next number must be less than 10 characters",
    workOrderSettingsPrefixTooShortMessage: "Work order prefix must be at least 3 characters",
    workOrderSettingsNextNumberTooShortMessage: "Work order next number must be at least 3 characters",
    workOrderSettingsPrefixRequiredMessage: "Work order prefix is required",
    workOrderSettingsNextNumberRequiredMessage: "Work order next number is required",
    workOrderSettingsPrefixInvalidMessage: "Work order prefix is invalid",
    workOrderSettingsNextNumberInvalidMessage: "Work order next number is invalid",
    workOrderSettingsPrefixTooLongMessage: "Work order prefix must be less than 10 characters",
    workOrderSettingsNextNumberTooLongMessage: "Work order next number must be less than 10 characters",
    workOrderSettingsPrefixTooShortMessage: "Work order prefix must be at least 3 characters",
    workOrderSettingsNextNumberTooShortMessage: "Work order next number must be at least 3 characters",
    workOrderSettingsPrefixPatternMessage: "Work order prefix must be alphanumeric",
    workOrderSettingsNextNumberPatternMessage: "Work order next number must be numeric",
    workOrderSettingsPrefixTooLongMessage: "Work order prefix must be less than 10 characters",
    workOrderSettingsNextNumberTooLongMessage: "Work order next number must be less than 10 characters",
    workOrderSettingsPrefixTooShortMessage: "Work order prefix must be at least 3 characters",
    workOrderSettingsNextNumberTooShortMessage: "Work order next number must be at least 3 characters",
    workOrderSettingsPrefixRequiredMessage: "Work order prefix is required",
    workOrderSettingsNextNumberRequiredMessage: "Work order next number is required",
    workOrderSettingsPrefixInvalidMessage: "Work order prefix is invalid",
    workOrderSettingsNextNumberInvalidMessage: "Work order next number is invalid",
    workOrderSettingsPrefixTooLongMessage: "Work order prefix must be less than 10 characters",
    workOrderSettingsNextNumberTooLongMessage: "Work order next number must be less than 10 characters",
    workOrderSettingsPrefixTooShortMessage: "Work order prefix must be at least 3 characters",
    workOrderSettingsNextNumberTooShortMessage: "Work order next number must be at least 3 characters",
    workOrderSettingsPrefixPatternMessage: "Work order prefix must be alphanumeric",
    workOrderSettingsNextNumberPatternMessage: "Work order next number must be numeric",
    workOrderSettingsPrefixTooLongMessage: "Work order prefix must be less than 10 characters",
    workOrderSettingsNextNumberTooLongMessage: "Work order next number must be less than 10 characters",
    workOrderSettingsPrefixTooShortMessage: "Work order prefix must be at least 3 characters",
    workOrderSettingsNextNumberTooShortMessage: "Work order next number must be at least 3 characters",
    workOrderSettingsPrefixRequiredMessage: "Work order prefix is required",
    workOrderSettingsNextNumberRequiredMessage: "Work order next number is required",
    workOrderSettingsPrefixInvalidMessage: "Work order prefix is invalid",
    workOrderSettingsNextNumberInvalidMessage: "Work order next number is invalid",
    workOrderSettingsPrefixTooLongMessage: "Work order prefix must be less than 10 characters",
    workOrderSettingsNextNumberTooLongMessage: "Work order next number must be less than 10 characters",
    workOrderSettingsPrefixTooShortMessage: "Work order prefix must be at least 3 characters",
    workOrderSettingsNextNumberTooShortMessage: "Work order next number must be at least 3 characters",
    workOrderSettingsPrefixPatternMessage: "Work order prefix must be alphanumeric",
    workOrderSettingsNextNumberPatternMessage: "Work order next number must be numeric",
    workOrderSettingsPrefixTooLongMessage: "Work order prefix must be less than 10 characters",
    workOrderSettingsNextNumberTooLongMessage: "Work order next number must be less than 10 characters",
    workOrderSettingsPrefixTooShortMessage: "Work order prefix must be at least 3 characters",
    workOrderSettingsNextNumberTooShortMessage: "Work order next number must be at least 3 characters",
    workOrderSettingsPrefixRequiredMessage: "Work order prefix is required",
    workOrderSettingsNextNumberRequiredMessage: "Work order next number is required",
    workOrderSettingsPrefixInvalidMessage: "Work order prefix is invalid",
    workOrderSettingsNextNumberInvalidMessage: "Work order next number is invalid",
    workOrderSettingsPrefixTooLongMessage: "Work order prefix must be less than 10 characters",
    workOrderSettingsNextNumberTooLongMessage: "Work order next number must be less than 10 characters",
    workOrderSettingsPrefixTooShortMessage: "Work order prefix must be at least 3 characters",
    workOrderSettingsNextNumberTooShortMessage: "Work order next number must be at least 3 characters",
    workOrderSettingsPrefixPatternMessage: "Work order prefix must be alphanumeric",
    workOrderSettingsNextNumberPatternMessage: "Work order next number must be numeric",
    workOrderSettingsPrefixTooLongMessage: "Work order prefix must be less than 10 characters",
    workOrderSettingsNextNumberTooLongMessage: "Work order next number must be less than 10 characters",
    workOrderSettingsPrefixTooShortMessage: "Work order prefix must be at least 3 characters",
    workOrderSettingsNextNumberTooShortMessage: "Work order next number must be at least 3 characters",
    workOrderSettingsPrefixRequiredMessage: "Work order prefix is required",
    workOrderSettingsNextNumberRequiredMessage: "Work order next number is required",
    workOrderSettingsPrefixInvalidMessage: "Work order prefix is invalid",
    workOrderSettingsNextNumberInvalidMessage: "Work order next number is invalid",
    workOrderSettingsPrefixTooLongMessage: "Work order prefix must be less than 10 characters",
    workOrderSettingsNextNumberTooLongMessage: "Work order next number must be less than 10 characters",
    workOrderSettingsPrefixTooShortMessage: "Work order prefix must be at least 3 characters",
    workOrderSettingsNextNumberTooShortMessage: "Work order next number must be at least 3 characters",
    workOrderSettingsPrefixPatternMessage: "Work order prefix must be alphanumeric",
    workOrderSettingsNextNumberPatternMessage: "Work order next number must be numeric",
    workOrderSettingsPrefixTooLongMessage: "Work order prefix must be less than 10 characters",
    workOrderSettingsNextNumberTooLongMessage: "Work order next number must be less than 10 characters",
    workOrderSettingsPrefixTooShortMessage: "Work order prefix must be at least 3 characters",
    workOrderSettingsNextNumberTooShortMessage: "Work order next number must be at least 3 characters",
    workOrderSettingsPrefixRequiredMessage: "Work order prefix is required",
    workOrderSettingsNextNumberRequiredMessage: "Work order next number is required",
    workOrderSettingsPrefixInvalidMessage: "Work order prefix is invalid",
    workOrderSettingsNextNumberInvalidMessage: "Work order next number is invalid",
    workOrderSettingsPrefixTooLongMessage: "Work order prefix must be less than 10 characters",
    workOrderSettingsNextNumberTooLongMessage: "Work order next number must be less than 10 characters",
    workOrderSettingsPrefixTooShortMessage: "Work order prefix must be at least 3 characters",
    workOrderSettingsNextNumberTooShortMessage: "Work order next number must be at least 3 characters",
    workOrderSettingsPrefixPatternMessage: "Work order prefix must be alphanumeric",
    workOrderSettingsNextNumberPatternMessage: "Work order next number must be numeric",
    workOrderSettingsPrefixTooLongMessage: "Work order prefix must be less than 10 characters",
    workOrderSettingsNextNumberTooLongMessage: "Work order next number must be less than 10 characters",
    workOrderSettingsPrefixTooShortMessage: "Work order prefix must be at least 3 characters",
    workOrderSettingsNextNumberTooShortMessage: "Work order next number must be at least 3 characters",
    workOrderSettingsPrefixRequiredMessage: "Work order prefix is required",
    workOrderSettingsNextNumberRequiredMessage: "Work order next number is required",
    workOrderSettingsPrefixInvalidMessage: "Work order prefix is invalid",
    workOrderSettingsNextNumberInvalidMessage: "Work order next number is invalid",
    workOrderSettingsPrefixTooLongMessage: "Work order prefix must be less than 10 characters",
    workOrderSettingsNextNumberTooLongMessage: "Work order next number must be less than 10 characters",
    workOrderSettingsPrefixTooShortMessage: "Work order prefix must be at least 3 characters",
    workOrderSettingsNextNumberTooShortMessage: "Work order next number must be at least 3 characters",
    workOrderSettingsPrefixPatternMessage: "Work order prefix must be alphanumeric",
    workOrderSettingsNextNumberPatternMessage: "Work order next number must be numeric",
    workOrderSettingsPrefixTooLongMessage: "Work order prefix must be less than 10 characters",
    workOrderSettingsNextNumberTooLongMessage: "Work order next number must be less than 10 characters",
    workOrderSettingsPrefixTooShortMessage: "Work order prefix must be at least 3 characters",
    workOrderSettingsNextNumberTooShortMessage: "Work order next number must be at least 3 characters",
    workOrderSettingsPrefixRequiredMessage: "Work order prefix is required",
    workOrderSettingsNextNumberRequiredMessage: "Work order next number is required",
    workOrderSettingsPrefixInvalidMessage: "Work order prefix is invalid",
    workOrderSettingsNextNumberInvalidMessage: "Work order next number is invalid",
    workOrderSettingsPrefixTooLongMessage: "Work order prefix must be less than 10 characters",
    workOrderSettingsNextNumberTooLongMessage: "Work order next number must be less than 10 characters",
    workOrderSettingsPrefixTooShortMessage: "Work order prefix must be at least 3 characters",
    workOrderSettingsNextNumberTooShortMessage: "Work order next number must be at least 3 characters",
    workOrderSettingsPrefixPatternMessage: "Work order prefix must be alphanumeric",
    workOrderSettingsNextNumberPatternMessage: "Work order next number must be numeric",
    workOrderSettingsPrefixTooLongMessage: "Work order prefix must be less than 10 characters",
    workOrderSettingsNextNumberTooLongMessage: "Work order next number must be less than 10 characters",
    workOrderSettingsPrefixTooShortMessage: "Work order prefix must be at least 3 characters",
    workOrderSettingsNextNumberTooShortMessage: "Work order next number must be at least 3 characters",
    workOrderSettingsPrefixRequiredMessage: "Work order prefix is required",
    workOrderSettingsNextNumberRequiredMessage: "Work order next number is required",
    workOrderSettingsPrefixInvalidMessage: "Work order prefix is invalid",
    workOrderSettingsNextNumberInvalidMessage: "Work order next number is invalid",
    workOrderSettingsPrefixTooLongMessage: "Work order prefix must be less than 10 characters",
    workOrderSettingsNextNumberTooLongMessage: "Work order next number must be less than 10 characters",
    workOrderSettingsPrefixTooShortMessage: "Work order prefix must be at least 3 characters",
    workOrderSettingsNextNumberTooShortMessage: "Work order next number must be at least 3 characters",
    workOrderSettingsPrefixPatternMessage: "Work order prefix must be alphanumeric",
    workOrderSettingsNextNumberPatternMessage: "Work order next number must be numeric",
    workOrderSettingsPrefixTooLongMessage: "Work order prefix must be less than 10 characters",
    workOrderSettingsNextNumberTooLongMessage: "Work order next number must be less than 10 characters",
    workOrderSettingsPrefixTooShortMessage: "Work order prefix must be at least 3 characters",
    workOrderSettingsNextNumberTooShortMessage: "Work order next number must be at least 3 characters",
    workOrderSettingsPrefixRequiredMessage: "Work order prefix is required",
    workOrderSettingsNextNumberRequiredMessage: "Work order next number is required",
    workOrderSettingsPrefixInvalidMessage: "Work order prefix is invalid",
    workOrderSettingsNextNumberInvalidMessage: "Work order next number is invalid",
    workOrderSettingsPrefixTooLongMessage: "Work order prefix must be less than 10 characters",
    workOrderSettingsNextNumberTooLongMessage: "Work order next number must be less than 10 characters",
    workOrderSettingsPrefixTooShortMessage: "Work order prefix must be at least 3 characters",
    workOrderSettingsNextNumberTooShortMessage: "Work order next number must be at least 3 characters",
    workOrderSettingsPrefixPatternMessage: "Work order prefix must be alphanumeric",
    workOrderSettingsNextNumberPatternMessage: "Work order next number must be numeric",
    workOrderSettingsPrefixTooLongMessage: "Work order prefix must be less than 10 characters",
    workOrderSettingsNextNumberTooLongMessage: "Work order next number must be less than 10 characters",
    workOrderSettingsPrefixTooShortMessage: "Work order prefix must be at least 3 characters",
    workOrderSettingsNextNumberTooShortMessage: "Work order next number must be at least 3 characters",
    workOrderSettingsPrefixRequiredMessage: "Work order prefix is required",
    workOrderSettingsNextNumberRequiredMessage: "Work order next number is required",
    workOrderSettingsPrefixInvalidMessage: "Work order prefix is invalid",
    workOrderSettingsNextNumberInvalidMessage: "Work order next number is invalid",
    workOrderSettingsPrefixTooLongMessage: "Work order prefix must be less than 10 characters",
    workOrderSettingsNextNumberTooLongMessage: "Work order next number must be less than 10 characters",
    workOrderSettingsPrefixTooShortMessage: "Work order prefix must be at least 3 characters",
    workOrderSettingsNextNumberTooShortMessage: "Work order next number must be at least 3 characters",
    workOrderSettingsPrefixPatternMessage: "Work order prefix must be alphanumeric",
    workOrderSettingsNextNumberPatternMessage: "Work order next number must be numeric",
    workOrderSettingsPrefixTooLongMessage: "Work order prefix must be less than 10 characters",
    workOrderSettingsNextNumberTooLongMessage: "Work order next number must be less than 10 characters",
    workOrderSettingsPrefixTooShortMessage: "Work order prefix must be at least 3 characters",
    workOrderSettingsNextNumberTooShortMessage: "Work order next number must be at least 3 characters",
    workOrderSettingsPrefixRequiredMessage: "Work order prefix is required",
    workOrderSettingsNextNumberRequiredMessage: "Work order next number is required",
    workOrderSettingsPrefixInvalidMessage: "Work order prefix is invalid",
    workOrderSettingsNextNumberInvalidMessage: "Work order next number is invalid",
    workOrderSettingsPrefixTooLongMessage: "Work order prefix must be less than 10 characters",
    workOrderSettingsNextNumberTooLongMessage: "Work order next number must be less than 10 characters",
    workOrderSettingsPrefixTooShortMessage: "Work order prefix must be at least 3 characters",
    workOrderSettingsNextNumberTooShortMessage: "Work order next number must be at least 3 characters",
    workOrderSettingsPrefixPatternMessage: "Work order prefix must be alphanumeric",
    workOrderSettingsNextNumberPatternMessage: "Work order next number must be numeric",
    workOrderSettingsPrefixTooLongMessage: "Work order prefix must be less than 10 characters",
    workOrderSettingsNextNumberTooLongMessage: "Work order next number must be less than 10 characters",
    workOrderSettingsPrefixTooShortMessage: "Work order prefix must be at least 3 characters",
    workOrderSettingsNextNumberTooShortMessage: "Work order next number must be at least 3 characters",
    workOrderSettingsPrefixRequiredMessage: "Work order prefix is required",
    workOrderSettingsNextNumberRequiredMessage: "Work order next number is required",
    workOrderSettingsPrefixInvalidMessage: "Work order prefix is invalid",
    workOrderSettingsNextNumberInvalidMessage: "Work order next number is invalid",
    workOrderSettingsPrefixTooLongMessage: "Work order prefix must be less than 10 characters",
    workOrderSettingsNextNumberTooLongMessage: "Work order next number must be less than 10 characters",
    workOrderSettingsPrefixTooShortMessage: "Work order prefix must be at least 3 characters",
    workOrderSettingsNextNumberTooShortMessage: "Work order next number must be at least 3 characters",
    workOrderSettingsPrefixPatternMessage: "Work order prefix must be alphanumeric",
    workOrderSettingsNextNumberPatternMessage: "Work order next number must be numeric",
    workOrderSettingsPrefixTooLongMessage: "Work order prefix must be less than 10 characters",
    workOrderSettingsNextNumberTooLongMessage: "Work order next number must be less than 10 characters",
    workOrderSettingsPrefixTooShortMessage: "Work order prefix must be at least 3 characters",
    workOrderSettingsNextNumberTooShortMessage: "Work order next number must be at least 3 characters",
    workOrderSettingsPrefixRequiredMessage: "Work order prefix is required",
    workOrderSettingsNextNumberRequiredMessage: "Work order next number is required",
    workOrderSettingsPrefixInvalidMessage: "Work order prefix is invalid",
    workOrderSettingsNextNumberInvalidMessage: "Work order next number is invalid",
    workOrderSettingsPrefixTooLongMessage: "Work order prefix must be less than 10 characters",
    workOrderSettingsNextNumberTooLongMessage: "Work order next number must be less than 10 characters",
    workOrderSettingsPrefixTooShortMessage: "Work order prefix must be at least 3 characters",
    workOrderSettingsNextNumberTooShortMessage: "Work order next number must be at least 3 characters",
    workOrderSettingsPrefixPatternMessage: "Work order prefix must be alphanumeric",
    workOrderSettingsNextNumberPatternMessage: "Work order next number must be numeric",
    workOrderSettingsPrefixTooLongMessage: "Work order prefix must be less than 10 characters",
    workOrderSettingsNextNumberTooLongMessage: "Work order next number must be less than 10 characters",
    workOrderSettingsPrefixTooShortMessage: "Work order prefix must be at least 3 characters",
    workOrderSettingsNextNumberTooShortMessage: "Work order next number must be at least 3 characters",
    workOrderSettingsPrefixRequiredMessage: "Work order prefix is required",
    workOrderSettingsNextNumberRequiredMessage: "Work order next number is required",
    workOrderSettingsPrefixInvalidMessage: "Work order prefix is invalid",
    workOrderSettingsNextNumberInvalidMessage: "Work order next number is invalid",
    workOrderSettingsPrefixTooLongMessage: "Work order prefix must be less than 10 characters",
    workOrderSettingsNextNumberTooLongMessage: "Work order next number must be less than 10 characters",
    workOrderSettingsPrefixTooShortMessage: "Work order prefix must be at least 3 characters",
    workOrderSettingsNextNumberTooShortMessage: "Work order next number must be at least 3 characters",
    workOrderSettingsPrefixPatternMessage: "Work order prefix must be alphanumeric",
    workOrderSettingsNextNumberPatternMessage: "Work order next number must be numeric",
    workOrderSettingsPrefixTooLongMessage: "Work order prefix must be less than 10 characters",
    workOrderSettingsNextNumberTooLongMessage: "Work order next number must be less than 10 characters",
    workOrderSettingsPrefixTooShortMessage: "Work order prefix must be at least 3 characters",
    workOrderSettingsNextNumberTooShortMessage: "Work order next number must be at least 3 characters",
    workOrderSettingsPrefixRequiredMessage: "Work order prefix is required",
    workOrderSettingsNextNumberRequiredMessage: "Work order next number is required",
    workOrderSettingsPrefixInvalidMessage: "Work order prefix is invalid",
    workOrderSettingsNextNumberInvalidMessage: "Work order next number is invalid",
    workOrderSettingsPrefixTooLongMessage: "Work order prefix must be less than 10 characters",
    workOrderSettingsNextNumberTooLongMessage: "Work order next number must be less than 10 characters",
    workOrderSettingsPrefixTooShortMessage: "Work order prefix must be at least 3 characters",
    workOrderSettingsNextNumberTooShortMessage: "Work order next number must be at least 3 characters",
    workOrderSettingsPrefixPatternMessage: "Work order prefix must be alphanumeric",
    workOrderSettingsNextNumberPatternMessage: "Work order next number must be numeric",
    workOrderSettingsPrefixTooLongMessage: "Work order prefix must be less than 10 characters",
    workOrderSettingsNextNumberTooLongMessage: "Work order next number must be less than 10 characters",
    workOrderSettingsPrefixTooShortMessage: "Work order prefix must be at least 3 characters",
    workOrderSettingsNextNumberTooShortMessage: "Work order next number must be at least 3 characters",
    workOrderSettingsPrefixRequiredMessage: "Work order prefix is required",
    workOrderSettingsNextNumberRequiredMessage: "Work order next number is required",
    workOrderSettingsPrefixInvalidMessage: "Work order prefix is invalid",
    workOrderSettingsNextNumberInvalidMessage: "Work order next number is invalid",
    workOrderSettingsPrefixTooLongMessage: "Work order prefix must be less than 10 characters",
    workOrderSettingsNextNumberTooLongMessage: "Work order next number must be less than 10 characters",
    workOrderSettingsPrefixTooShortMessage: "Work order prefix must be at least 3 characters",
    workOrderSettingsNextNumberTooShortMessage: "Work order next number must be at least 3 characters",
    workOrderSettingsPrefixPatternMessage: "Work order prefix must be alphanumeric",
    workOrderSettingsNextNumberPatternMessage: "Work order next number must be numeric",
    workOrderSettingsPrefixTooLongMessage: "Work order prefix must be less than 10 characters",
    workOrderSettingsNextNumberTooLongMessage: "Work order next number must be less than 10 characters",
    workOrderSettingsPrefixTooShortMessage: "Work order prefix must be at least 3 characters",
    workOrderSettingsNextNumberTooShortMessage: "Work order next number must be at least 3 characters",
    workOrderSettingsPrefixRequiredMessage: "Work order prefix is required",
    workOrderSettingsNextNumberRequiredMessage: "Work order next number is required",
    workOrderSettingsPrefixInvalidMessage: "Work order prefix is invalid",
    workOrderSettingsNextNumberInvalidMessage: "Work order next number is invalid",
    workOrderSettingsPrefixTooLongMessage: "Work order prefix must be less than 10 characters",
    workOrderSettingsNextNumberTooLongMessage: "Work order next number must be less than 10 characters",
    workOrderSettingsPrefixTooShortMessage: "Work order prefix must be at least 3 characters",
    workOrderSettingsNextNumberTooShortMessage: "Work order next number must be at least 3 characters",
    workOrderSettingsPrefixPatternMessage: "Work order prefix must be alphanumeric",
    workOrderSettingsNextNumberPatternMessage: "Work order next number must be numeric",
    workOrderSettingsPrefixTooLongMessage: "Work order prefix must be less than 10 characters",
    workOrderSettingsNextNumberTooLongMessage: "Work order next number must be less than 10 characters",
    workOrderSettingsPrefixTooShortMessage: "Work order prefix must be at least 3 characters",
    workOrderSettingsNextNumberTooShortMessage: "Work order next number must be at least 3 characters",
    workOrderSettingsPrefixRequiredMessage: "Work order prefix is required",
    workOrderSettingsNextNumberRequiredMessage: "Work order next number is required",
    workOrderSettingsPrefixInvalidMessage: "Work order prefix is invalid",
    workOrderSettingsNextNumberInvalidMessage: "Work order next number is invalid",
    workOrderSettingsPrefixTooLongMessage: "Work order prefix must be less than 10 characters",
    workOrderSettingsNextNumberTooLongMessage: "Work order next number must be less than 10 characters",
    workOrderSettingsPrefixTooShortMessage: "Work order prefix must be at least 3 characters",
    workOrderSettingsNextNumberTooShortMessage: "Work order next number must be at least 3 characters",
    workOrderSettingsPrefixPatternMessage: "Work order prefix must be alphanumeric",
    workOrderSettingsNextNumberPatternMessage: "Work order next number must be numeric",
    workOrderSettingsPrefixTooLongMessage: "Work order prefix must be less than 10 characters",
    workOrderSettingsNextNumberTooLongMessage: "Work order next number must be less than 10 characters",
    workOrderSettingsPrefixTooShortMessage: "Work order prefix must be at least 3 characters",
    workOrderSettingsNextNumberTooShortMessage: "Work order next number must be at least 3 characters",
    workOrderSettingsPrefixRequiredMessage: "Work order prefix is required",
    workOrderSettingsNextNumberRequiredMessage: "Work order next number is required",
    workOrderSettingsPrefixInvalidMessage: "Work order prefix is invalid",
    workOrderSettingsNextNumberInvalidMessage: "Work order next number is invalid",
    workOrderSettingsPrefixTooLongMessage: "Work order prefix must be less than 10 characters",
    workOrderSettingsNextNumberTooLongMessage: "Work order next number must be less than 10 characters",
    workOrderSettingsPrefixTooShortMessage: "Work order prefix must be at least 3 characters",
    workOrderSettingsNextNumberTooShortMessage: "Work order next number must be at least 3 characters",
    workOrderSettingsPrefixPatternMessage: "Work order prefix must be alphanumeric",
    workOrderSettingsNextNumberPatternMessage: "Work order next number must be numeric",
    workOrderSettingsPrefixTooLongMessage: "Work order prefix must be less than 10 characters",
    workOrderSettingsNextNumberTooLongMessage: "Work order next number must be less than 10 characters",
    workOrderSettingsPrefixTooShortMessage: "Work order prefix must be at least 3 characters",
    workOrderSettingsNextNumberTooShortMessage: "Work order next number must be at least 3 characters",
    workOrderSettingsPrefixRequiredMessage: "Work order prefix is required",
    workOrderSettingsNextNumberRequiredMessage: "Work order next number is required",
    workOrderSettingsPrefixInvalidMessage: "Work order prefix is invalid",
    workOrderSettingsNextNumberInvalidMessage: "Work order next number is invalid",
    workOrderSettingsPrefixTooLongMessage: "Work order prefix must be less than 10 characters",
    workOrderSettingsNextNumberTooLongMessage: "Work order next number must be less than 10 characters",
    workOrderSettingsPrefixTooShortMessage: "Work order prefix must be at least 3 characters",
    workOrderSettingsNextNumberTooShortMessage: "Work order next number must be at least 3 characters",
    workOrderSettingsPrefixPatternMessage: "Work order prefix must be alphanumeric",
    workOrderSettingsNextNumberPatternMessage: "Work order next number must be numeric",
    workOrderSettingsPrefixTooLongMessage: "Work order prefix must be less than 10 characters",
    workOrderSettingsNextNumberTooLongMessage: "Work order next number must be less than 10 characters",
    workOrderSettingsPrefixTooShortMessage: "Work order prefix must be at least 3 characters",
    workOrderSettingsNextNumberTooShortMessage: "Work order next number must be at least 3 characters",
    workOrder
