// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aqrnzsuhvnvnssbacspu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFxcm56c3Vodm52bnNzYmFjc3B1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4NTgwNTMsImV4cCI6MjA1OTQzNDA1M30.EEGWx8L5WmJmToXr9V0t2rViXoOWNawuLArPLoj5hHw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);